allowBuilds:
  '@prisma/engines': true
  esbuild: true
  msw: true
  prisma: true
  sharp: true
  unrs-resolver: true

ignoredBuiltDependencies:
  - esbuild
  - msw
  - sharp
  - unrs-resolver

onlyBuiltDependencies:
  - '@prisma/engines'
  - prisma
